# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4_518cEOoN0ruPMy52BV5GMdiPaCIou
"""

import numpy as np


X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

Y = np.array([[0],
              [1],
              [1],
              [0]])


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

np.random.seed(1)

W1 = np.random.rand(2, 2)
W2 = np.random.rand(2, 1)

b1 = np.random.rand(1, 2)
b2 = np.random.rand(1, 1)

learning_rate = 0.5


for epoch in range(10000):


    hidden = sigmoid(np.dot(X, W1) + b1)
    output = sigmoid(np.dot(hidden, W2) + b2)

    error = Y - output

    output_delta = error * sigmoid_derivative(output)
    hidden_error = output_delta.dot(W2.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden)

    W2 += hidden.T.dot(output_delta) * learning_rate
    W1 += X.T.dot(hidden_delta) * learning_rate

    b2 += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
    b1 += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate

hidden = sigmoid(np.dot(X, W1) + b1)
output = sigmoid(np.dot(hidden, W2) + b2)

print("Actual Output:")
print(Y)

print("\nPredicted Output:")
print(np.round(output, 3))

prediction = (output >= 0.5).astype(int)

print("\nPredicted Classes:")
print(prediction)

accuracy = np.mean(prediction == Y) * 100
print("\nAccuracy:", accuracy, "%")