# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWxjsIGvPWXoZsk8TGZES96D4QkJ3PWm
"""

data = [
    ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']
]


X = [row[:-1] for row in data]
Y = [row[-1] for row in data]


S = ['0'] * len(X[0])


G = [['?'] * len(X[0])]


for i in range(len(X)):

    print("\nExample", i + 1, ":", X[i], "=>", Y[i])


    if Y[i] == 'Yes':

        for j in range(len(S)):


            if S[j] == '0':
                S[j] = X[i][j]


            elif S[j] != X[i][j]:
                S[j] = '?'


        G = [
            g for g in G
            if all(g[j] == '?' or g[j] == X[i][j]
                   for j in range(len(S)))
        ]


    else:

        new_G = []

        for g in G:

            for j in range(len(S)):

                # Specialize G
                if g[j] == '?' and S[j] != '?':

                    if S[j] != X[i][j]:

                        new_hypothesis = g.copy()
                        new_hypothesis[j] = S[j]

                        new_G.append(new_hypothesis)

        G = new_G


    print("Specific Boundary S =", S)
    print("General Boundary G =", G)

print("\n-----------------------------")
print("FINAL RESULT")
print("-----------------------------")

print("Specific Boundary S:")
print(S)

print("\nGeneral Boundary G:")
for g in G:
    print(g)