# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoVcmGyNnWiE8V0va2qhIEiFdEyA5CUN
"""

def find_s(training_data):
    hypothesis = None

    for example in training_data:
        attributes = example[:-1]
        target = example[-1]


        if target == "Yes":
            if hypothesis is None:
                hypothesis = attributes.copy()
            else:
                for i in range(len(hypothesis)):
                    if hypothesis[i] != attributes[i]:
                        hypothesis[i] = "?"

    return hypothesis



training_data = [
    ["Sunny", "Warm", "Normal", "Strong", "Warm", "Same", "Yes"],
    ["Sunny", "Warm", "High", "Strong", "Warm", "Same", "Yes"],
    ["Rainy", "Cold", "High", "Strong", "Warm", "Change", "No"],
    ["Sunny", "Warm", "High", "Strong", "Cool", "Change", "Yes"]
]


hypothesis = find_s(training_data)

print("Most Specific Hypothesis:")
print(hypothesis)